TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += attocube.db
DATA += attocube.proto

#=======================================
include $(TOP)/configure/RULES
